name: workflow_01
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workflow_02:
        description: 'Ù‹Workflow 2 which will be triggered'
        required: true
        default: 'workflow_02'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: ':ambiaahmed1'

      workflow2_repo_github:
        description: 'RepositoryB'
        required: true
        default: ':repoName'