on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repo_token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
          event_type: event_name
          repositories: |
            ambiaahmed1/RepositoryA
            ambiaahmed1/RepositoryB
          client_payload: '{"github": ${{ toJson(github) }}}'