name: Selenium-Maven-Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'  # Specify the distribution (e.g., 'adopt', 'openjdk')
    
    - name:  Install Google Chrome # Using shell script to install Google Chrome
      run:   |
              chmod +x ./scripts/InstallChrome.sh
                          ./scripts/InstallChrome.sh 
    

    - name: Build with Maven
      run: mvn clean install

    - name: Run Selenium Tests
      run: mvn test

    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: target/surefire-reports # Adjust the path as per your project structure
