name: Trigger External Workflow

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Trigger External Workflow in Repository B"]
    types:
      - completed

jobs:
  trigger_external:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Repository B
        env:
          TOKEN: ${{ secrets.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 }}
        run: |
          curl -X POST -H "Authorization: token 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" -H "Accept: application/vnd.github.everest-preview+json" https://api.github.com/repos/ambiaahmed1/ProjectB/dispatches --data "{\"event_type\": \"trigger-external-workflow\"}"